// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dfuse/solana/codec/v1/codec.proto

package pbcodec

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Slot struct {
	Id                     string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Number                 uint64         `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	PreviousId             string         `protobuf:"bytes,3,opt,name=previous_id,json=previousId,proto3" json:"previous_id,omitempty"`
	Version                uint32         `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Block                  *Block         `protobuf:"bytes,5,opt,name=block,proto3" json:"block,omitempty"`
	Transactions           []*Transaction `protobuf:"bytes,7,rep,name=transactions,proto3" json:"transactions,omitempty"`
	TransactionCount       uint32         `protobuf:"varint,8,opt,name=transaction_count,json=transactionCount,proto3" json:"transaction_count,omitempty"`
	HasSplitAccountChanges bool           `protobuf:"varint,9,opt,name=has_split_account_changes,json=hasSplitAccountChanges,proto3" json:"has_split_account_changes,omitempty"`
	AccountChangesFileRef  string         `protobuf:"bytes,10,opt,name=account_changes_file_ref,json=accountChangesFileRef,proto3" json:"account_changes_file_ref,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}       `json:"-"`
	XXX_unrecognized       []byte         `json:"-"`
	XXX_sizecache          int32          `json:"-"`
}

func (m *Slot) Reset()         { *m = Slot{} }
func (m *Slot) String() string { return proto.CompactTextString(m) }
func (*Slot) ProtoMessage()    {}
func (*Slot) Descriptor() ([]byte, []int) {
	return fileDescriptor_10cf9f0a2b7e0e4b, []int{0}
}

func (m *Slot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Slot.Unmarshal(m, b)
}
func (m *Slot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Slot.Marshal(b, m, deterministic)
}
func (m *Slot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Slot.Merge(m, src)
}
func (m *Slot) XXX_Size() int {
	return xxx_messageInfo_Slot.Size(m)
}
func (m *Slot) XXX_DiscardUnknown() {
	xxx_messageInfo_Slot.DiscardUnknown(m)
}

var xxx_messageInfo_Slot proto.InternalMessageInfo

func (m *Slot) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Slot) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Slot) GetPreviousId() string {
	if m != nil {
		return m.PreviousId
	}
	return ""
}

func (m *Slot) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Slot) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *Slot) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *Slot) GetTransactionCount() uint32 {
	if m != nil {
		return m.TransactionCount
	}
	return 0
}

func (m *Slot) GetHasSplitAccountChanges() bool {
	if m != nil {
		return m.HasSplitAccountChanges
	}
	return false
}

func (m *Slot) GetAccountChangesFileRef() string {
	if m != nil {
		return m.AccountChangesFileRef
	}
	return ""
}

type Block struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Number               uint64   `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Height               uint64   `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	PreviousId           string   `protobuf:"bytes,4,opt,name=previous_id,json=previousId,proto3" json:"previous_id,omitempty"`
	PreviousBlockSlot    uint64   `protobuf:"varint,5,opt,name=previous_block_slot,json=previousBlockSlot,proto3" json:"previous_block_slot,omitempty"`
	GenesisUnixTimestamp uint64   `protobuf:"varint,6,opt,name=genesis_unix_timestamp,json=genesisUnixTimestamp,proto3" json:"genesis_unix_timestamp,omitempty"`
	ClockUnixTimestamp   uint64   `protobuf:"varint,7,opt,name=clock_unix_timestamp,json=clockUnixTimestamp,proto3" json:"clock_unix_timestamp,omitempty"`
	RootNum              uint64   `protobuf:"varint,8,opt,name=root_num,json=rootNum,proto3" json:"root_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_10cf9f0a2b7e0e4b, []int{1}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Block) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Block) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Block) GetPreviousId() string {
	if m != nil {
		return m.PreviousId
	}
	return ""
}

func (m *Block) GetPreviousBlockSlot() uint64 {
	if m != nil {
		return m.PreviousBlockSlot
	}
	return 0
}

func (m *Block) GetGenesisUnixTimestamp() uint64 {
	if m != nil {
		return m.GenesisUnixTimestamp
	}
	return 0
}

func (m *Block) GetClockUnixTimestamp() uint64 {
	if m != nil {
		return m.ClockUnixTimestamp
	}
	return 0
}

func (m *Block) GetRootNum() uint64 {
	if m != nil {
		return m.RootNum
	}
	return 0
}

type Batch struct {
	Transactions         []*Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Batch) Reset()         { *m = Batch{} }
func (m *Batch) String() string { return proto.CompactTextString(m) }
func (*Batch) ProtoMessage()    {}
func (*Batch) Descriptor() ([]byte, []int) {
	return fileDescriptor_10cf9f0a2b7e0e4b, []int{2}
}

func (m *Batch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Batch.Unmarshal(m, b)
}
func (m *Batch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Batch.Marshal(b, m, deterministic)
}
func (m *Batch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Batch.Merge(m, src)
}
func (m *Batch) XXX_Size() int {
	return xxx_messageInfo_Batch.Size(m)
}
func (m *Batch) XXX_DiscardUnknown() {
	xxx_messageInfo_Batch.DiscardUnknown(m)
}

var xxx_messageInfo_Batch proto.InternalMessageInfo

func (m *Batch) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

// Bundled in separate files, referenced by `account_changes_file_ref`
type AccountChangesBundle struct {
	// Maps to the index of the `repeated` field for Block::transactions
	Transactions         []*AccountChangesPerTrxIndex `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *AccountChangesBundle) Reset()         { *m = AccountChangesBundle{} }
func (m *AccountChangesBundle) String() string { return proto.CompactTextString(m) }
func (*AccountChangesBundle) ProtoMessage()    {}
func (*AccountChangesBundle) Descriptor() ([]byte, []int) {
	return fileDescriptor_10cf9f0a2b7e0e4b, []int{3}
}

func (m *AccountChangesBundle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountChangesBundle.Unmarshal(m, b)
}
func (m *AccountChangesBundle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountChangesBundle.Marshal(b, m, deterministic)
}
func (m *AccountChangesBundle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountChangesBundle.Merge(m, src)
}
func (m *AccountChangesBundle) XXX_Size() int {
	return xxx_messageInfo_AccountChangesBundle.Size(m)
}
func (m *AccountChangesBundle) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountChangesBundle.DiscardUnknown(m)
}

var xxx_messageInfo_AccountChangesBundle proto.InternalMessageInfo

func (m *AccountChangesBundle) GetTransactions() []*AccountChangesPerTrxIndex {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type AccountChangesPerTrxIndex struct {
	// Maps to the index within the `repeated` field of the proto for
	// Transaction::instructions
	Instructions         []*AccountChangesPerInstruction `protobuf:"bytes,1,rep,name=instructions,proto3" json:"instructions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *AccountChangesPerTrxIndex) Reset()         { *m = AccountChangesPerTrxIndex{} }
func (m *AccountChangesPerTrxIndex) String() string { return proto.CompactTextString(m) }
func (*AccountChangesPerTrxIndex) ProtoMessage()    {}
func (*AccountChangesPerTrxIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_10cf9f0a2b7e0e4b, []int{4}
}

func (m *AccountChangesPerTrxIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountChangesPerTrxIndex.Unmarshal(m, b)
}
func (m *AccountChangesPerTrxIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountChangesPerTrxIndex.Marshal(b, m, deterministic)
}
func (m *AccountChangesPerTrxIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountChangesPerTrxIndex.Merge(m, src)
}
func (m *AccountChangesPerTrxIndex) XXX_Size() int {
	return xxx_messageInfo_AccountChangesPerTrxIndex.Size(m)
}
func (m *AccountChangesPerTrxIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountChangesPerTrxIndex.DiscardUnknown(m)
}

var xxx_messageInfo_AccountChangesPerTrxIndex proto.InternalMessageInfo

func (m *AccountChangesPerTrxIndex) GetInstructions() []*AccountChangesPerInstruction {
	if m != nil {
		return m.Instructions
	}
	return nil
}

type AccountChangesPerInstruction struct {
	// Data to be put in Instruction::account_changes
	Changes              []*AccountChange `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AccountChangesPerInstruction) Reset()         { *m = AccountChangesPerInstruction{} }
func (m *AccountChangesPerInstruction) String() string { return proto.CompactTextString(m) }
func (*AccountChangesPerInstruction) ProtoMessage()    {}
func (*AccountChangesPerInstruction) Descriptor() ([]byte, []int) {
	return fileDescriptor_10cf9f0a2b7e0e4b, []int{5}
}

func (m *AccountChangesPerInstruction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountChangesPerInstruction.Unmarshal(m, b)
}
func (m *AccountChangesPerInstruction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountChangesPerInstruction.Marshal(b, m, deterministic)
}
func (m *AccountChangesPerInstruction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountChangesPerInstruction.Merge(m, src)
}
func (m *AccountChangesPerInstruction) XXX_Size() int {
	return xxx_messageInfo_AccountChangesPerInstruction.Size(m)
}
func (m *AccountChangesPerInstruction) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountChangesPerInstruction.DiscardUnknown(m)
}

var xxx_messageInfo_AccountChangesPerInstruction proto.InternalMessageInfo

func (m *AccountChangesPerInstruction) GetChanges() []*AccountChange {
	if m != nil {
		return m.Changes
	}
	return nil
}

type Transaction struct {
	// The transaction ID corresponds to the _first_
	// signature. Additional signatures are in `additional_signatures`.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// slot_num could be zero for non-executed transactions
	SlotNum uint64 `protobuf:"varint,2,opt,name=slot_num,json=slotNum,proto3" json:"slot_num,omitempty"`
	// slot_hash could be empty for non-executed transactions
	SlotHash string `protobuf:"bytes,3,opt,name=slot_hash,json=slotHash,proto3" json:"slot_hash,omitempty"`
	// Index from within a single Slot, deterministically ordered to the
	// best of our ability using the transaction ID as a sort key for
	// the batch of transactions executed in parallel.
	Index                uint64         `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	AdditionalSignatures []string       `protobuf:"bytes,5,rep,name=additional_signatures,json=additionalSignatures,proto3" json:"additional_signatures,omitempty"`
	Header               *MessageHeader `protobuf:"bytes,6,opt,name=header,proto3" json:"header,omitempty"`
	// From the original Message object
	AccountKeys []string `protobuf:"bytes,7,rep,name=account_keys,json=accountKeys,proto3" json:"account_keys,omitempty"`
	// From the original Message object
	RecentBlockhash string `protobuf:"bytes,8,opt,name=recent_blockhash,json=recentBlockhash,proto3" json:"recent_blockhash,omitempty"`
	// What follows Once executed these can be set:
	LogMessages []string `protobuf:"bytes,12,rep,name=log_messages,json=logMessages,proto3" json:"log_messages,omitempty"`
	// Instructions, containing both top-level and nested transactions
	Instructions         []*Instruction `protobuf:"bytes,13,rep,name=instructions,proto3" json:"instructions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_10cf9f0a2b7e0e4b, []int{6}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Transaction) GetSlotNum() uint64 {
	if m != nil {
		return m.SlotNum
	}
	return 0
}

func (m *Transaction) GetSlotHash() string {
	if m != nil {
		return m.SlotHash
	}
	return ""
}

func (m *Transaction) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Transaction) GetAdditionalSignatures() []string {
	if m != nil {
		return m.AdditionalSignatures
	}
	return nil
}

func (m *Transaction) GetHeader() *MessageHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Transaction) GetAccountKeys() []string {
	if m != nil {
		return m.AccountKeys
	}
	return nil
}

func (m *Transaction) GetRecentBlockhash() string {
	if m != nil {
		return m.RecentBlockhash
	}
	return ""
}

func (m *Transaction) GetLogMessages() []string {
	if m != nil {
		return m.LogMessages
	}
	return nil
}

func (m *Transaction) GetInstructions() []*Instruction {
	if m != nil {
		return m.Instructions
	}
	return nil
}

type MessageHeader struct {
	NumRequiredSignatures       uint32   `protobuf:"varint,1,opt,name=num_required_signatures,json=numRequiredSignatures,proto3" json:"num_required_signatures,omitempty"`
	NumReadonlySignedAccounts   uint32   `protobuf:"varint,2,opt,name=num_readonly_signed_accounts,json=numReadonlySignedAccounts,proto3" json:"num_readonly_signed_accounts,omitempty"`
	NumReadonlyUnsignedAccounts uint32   `protobuf:"varint,3,opt,name=num_readonly_unsigned_accounts,json=numReadonlyUnsignedAccounts,proto3" json:"num_readonly_unsigned_accounts,omitempty"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-"`
	XXX_unrecognized            []byte   `json:"-"`
	XXX_sizecache               int32    `json:"-"`
}

func (m *MessageHeader) Reset()         { *m = MessageHeader{} }
func (m *MessageHeader) String() string { return proto.CompactTextString(m) }
func (*MessageHeader) ProtoMessage()    {}
func (*MessageHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_10cf9f0a2b7e0e4b, []int{7}
}

func (m *MessageHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageHeader.Unmarshal(m, b)
}
func (m *MessageHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageHeader.Marshal(b, m, deterministic)
}
func (m *MessageHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageHeader.Merge(m, src)
}
func (m *MessageHeader) XXX_Size() int {
	return xxx_messageInfo_MessageHeader.Size(m)
}
func (m *MessageHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageHeader.DiscardUnknown(m)
}

var xxx_messageInfo_MessageHeader proto.InternalMessageInfo

func (m *MessageHeader) GetNumRequiredSignatures() uint32 {
	if m != nil {
		return m.NumRequiredSignatures
	}
	return 0
}

func (m *MessageHeader) GetNumReadonlySignedAccounts() uint32 {
	if m != nil {
		return m.NumReadonlySignedAccounts
	}
	return 0
}

func (m *MessageHeader) GetNumReadonlyUnsignedAccounts() uint32 {
	if m != nil {
		return m.NumReadonlyUnsignedAccounts
	}
	return 0
}

type Instruction struct {
	ProgramId            string           `protobuf:"bytes,3,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"`
	AccountKeys          []string         `protobuf:"bytes,4,rep,name=account_keys,json=accountKeys,proto3" json:"account_keys,omitempty"`
	Data                 []byte           `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Ordinal              uint32           `protobuf:"varint,6,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	ParentOrdinal        uint32           `protobuf:"varint,7,opt,name=parent_ordinal,json=parentOrdinal,proto3" json:"parent_ordinal,omitempty"`
	Depth                uint32           `protobuf:"varint,8,opt,name=depth,proto3" json:"depth,omitempty"`
	BalanceChanges       []*BalanceChange `protobuf:"bytes,9,rep,name=balance_changes,json=balanceChanges,proto3" json:"balance_changes,omitempty"`
	AccountChanges       []*AccountChange `protobuf:"bytes,10,rep,name=account_changes,json=accountChanges,proto3" json:"account_changes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Instruction) Reset()         { *m = Instruction{} }
func (m *Instruction) String() string { return proto.CompactTextString(m) }
func (*Instruction) ProtoMessage()    {}
func (*Instruction) Descriptor() ([]byte, []int) {
	return fileDescriptor_10cf9f0a2b7e0e4b, []int{8}
}

func (m *Instruction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instruction.Unmarshal(m, b)
}
func (m *Instruction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instruction.Marshal(b, m, deterministic)
}
func (m *Instruction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instruction.Merge(m, src)
}
func (m *Instruction) XXX_Size() int {
	return xxx_messageInfo_Instruction.Size(m)
}
func (m *Instruction) XXX_DiscardUnknown() {
	xxx_messageInfo_Instruction.DiscardUnknown(m)
}

var xxx_messageInfo_Instruction proto.InternalMessageInfo

func (m *Instruction) GetProgramId() string {
	if m != nil {
		return m.ProgramId
	}
	return ""
}

func (m *Instruction) GetAccountKeys() []string {
	if m != nil {
		return m.AccountKeys
	}
	return nil
}

func (m *Instruction) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Instruction) GetOrdinal() uint32 {
	if m != nil {
		return m.Ordinal
	}
	return 0
}

func (m *Instruction) GetParentOrdinal() uint32 {
	if m != nil {
		return m.ParentOrdinal
	}
	return 0
}

func (m *Instruction) GetDepth() uint32 {
	if m != nil {
		return m.Depth
	}
	return 0
}

func (m *Instruction) GetBalanceChanges() []*BalanceChange {
	if m != nil {
		return m.BalanceChanges
	}
	return nil
}

func (m *Instruction) GetAccountChanges() []*AccountChange {
	if m != nil {
		return m.AccountChanges
	}
	return nil
}

type BalanceChange struct {
	Pubkey               string   `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	PrevLamports         uint64   `protobuf:"varint,2,opt,name=prev_lamports,json=prevLamports,proto3" json:"prev_lamports,omitempty"`
	NewLamports          uint64   `protobuf:"varint,3,opt,name=new_lamports,json=newLamports,proto3" json:"new_lamports,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceChange) Reset()         { *m = BalanceChange{} }
func (m *BalanceChange) String() string { return proto.CompactTextString(m) }
func (*BalanceChange) ProtoMessage()    {}
func (*BalanceChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_10cf9f0a2b7e0e4b, []int{9}
}

func (m *BalanceChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceChange.Unmarshal(m, b)
}
func (m *BalanceChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceChange.Marshal(b, m, deterministic)
}
func (m *BalanceChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceChange.Merge(m, src)
}
func (m *BalanceChange) XXX_Size() int {
	return xxx_messageInfo_BalanceChange.Size(m)
}
func (m *BalanceChange) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceChange.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceChange proto.InternalMessageInfo

func (m *BalanceChange) GetPubkey() string {
	if m != nil {
		return m.Pubkey
	}
	return ""
}

func (m *BalanceChange) GetPrevLamports() uint64 {
	if m != nil {
		return m.PrevLamports
	}
	return 0
}

func (m *BalanceChange) GetNewLamports() uint64 {
	if m != nil {
		return m.NewLamports
	}
	return 0
}

type AccountChange struct {
	Pubkey               string   `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	PrevData             []byte   `protobuf:"bytes,2,opt,name=prev_data,json=prevData,proto3" json:"prev_data,omitempty"`
	NewData              []byte   `protobuf:"bytes,3,opt,name=new_data,json=newData,proto3" json:"new_data,omitempty"`
	NewDataLength        uint64   `protobuf:"varint,4,opt,name=new_data_length,json=newDataLength,proto3" json:"new_data_length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountChange) Reset()         { *m = AccountChange{} }
func (m *AccountChange) String() string { return proto.CompactTextString(m) }
func (*AccountChange) ProtoMessage()    {}
func (*AccountChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_10cf9f0a2b7e0e4b, []int{10}
}

func (m *AccountChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountChange.Unmarshal(m, b)
}
func (m *AccountChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountChange.Marshal(b, m, deterministic)
}
func (m *AccountChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountChange.Merge(m, src)
}
func (m *AccountChange) XXX_Size() int {
	return xxx_messageInfo_AccountChange.Size(m)
}
func (m *AccountChange) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountChange.DiscardUnknown(m)
}

var xxx_messageInfo_AccountChange proto.InternalMessageInfo

func (m *AccountChange) GetPubkey() string {
	if m != nil {
		return m.Pubkey
	}
	return ""
}

func (m *AccountChange) GetPrevData() []byte {
	if m != nil {
		return m.PrevData
	}
	return nil
}

func (m *AccountChange) GetNewData() []byte {
	if m != nil {
		return m.NewData
	}
	return nil
}

func (m *AccountChange) GetNewDataLength() uint64 {
	if m != nil {
		return m.NewDataLength
	}
	return 0
}

func init() {
	proto.RegisterType((*Slot)(nil), "dfuse.solana.codec.v1.Slot")
	proto.RegisterType((*Block)(nil), "dfuse.solana.codec.v1.Block")
	proto.RegisterType((*Batch)(nil), "dfuse.solana.codec.v1.Batch")
	proto.RegisterType((*AccountChangesBundle)(nil), "dfuse.solana.codec.v1.AccountChangesBundle")
	proto.RegisterType((*AccountChangesPerTrxIndex)(nil), "dfuse.solana.codec.v1.AccountChangesPerTrxIndex")
	proto.RegisterType((*AccountChangesPerInstruction)(nil), "dfuse.solana.codec.v1.AccountChangesPerInstruction")
	proto.RegisterType((*Transaction)(nil), "dfuse.solana.codec.v1.Transaction")
	proto.RegisterType((*MessageHeader)(nil), "dfuse.solana.codec.v1.MessageHeader")
	proto.RegisterType((*Instruction)(nil), "dfuse.solana.codec.v1.Instruction")
	proto.RegisterType((*BalanceChange)(nil), "dfuse.solana.codec.v1.BalanceChange")
	proto.RegisterType((*AccountChange)(nil), "dfuse.solana.codec.v1.AccountChange")
}

func init() {
	proto.RegisterFile("dfuse/solana/codec/v1/codec.proto", fileDescriptor_10cf9f0a2b7e0e4b)
}

var fileDescriptor_10cf9f0a2b7e0e4b = []byte{
	// 1006 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x6d, 0x6f, 0xe3, 0x44,
	0x10, 0x56, 0x12, 0xa7, 0x49, 0x26, 0x49, 0xef, 0x6e, 0x49, 0x8b, 0xa3, 0x2b, 0x90, 0x0b, 0x2f,
	0x0a, 0x42, 0xa4, 0x77, 0x2d, 0x02, 0x21, 0x10, 0xe8, 0x52, 0x74, 0xba, 0x8a, 0x7b, 0x41, 0xdb,
	0x9e, 0x90, 0xf8, 0x80, 0xb5, 0xb1, 0xb7, 0xf1, 0xaa, 0xf6, 0xae, 0xf1, 0xda, 0x7d, 0xf9, 0x03,
	0xf0, 0x13, 0xf8, 0xc0, 0x6f, 0xe2, 0x3b, 0x3f, 0x07, 0xed, 0x78, 0x7d, 0x8d, 0xd3, 0xa6, 0x2a,
	0x7c, 0xf3, 0xcc, 0xf3, 0xcc, 0xcc, 0xee, 0x3e, 0xb3, 0x3b, 0x86, 0x47, 0xc1, 0x49, 0xae, 0xf9,
	0xae, 0x56, 0x11, 0x93, 0x6c, 0xd7, 0x57, 0x01, 0xf7, 0x77, 0xcf, 0x9e, 0x14, 0x1f, 0xd3, 0x24,
	0x55, 0x99, 0x22, 0x5b, 0x48, 0x99, 0x16, 0x94, 0x69, 0x81, 0x9c, 0x3d, 0x19, 0xff, 0xde, 0x00,
	0xe7, 0x28, 0x52, 0x19, 0xd9, 0x84, 0xba, 0x08, 0xdc, 0xda, 0xa8, 0x36, 0xe9, 0xd0, 0xba, 0x08,
	0xc8, 0x36, 0x6c, 0xc8, 0x3c, 0x9e, 0xf3, 0xd4, 0xad, 0x8f, 0x6a, 0x13, 0x87, 0x5a, 0x8b, 0x7c,
	0x00, 0xdd, 0x24, 0xe5, 0x67, 0x42, 0xe5, 0xda, 0x13, 0x81, 0xdb, 0xc0, 0x00, 0x28, 0x5d, 0x87,
	0x01, 0x71, 0xa1, 0x75, 0xc6, 0x53, 0x2d, 0x94, 0x74, 0x9d, 0x51, 0x6d, 0xd2, 0xa7, 0xa5, 0x49,
	0xf6, 0xa0, 0x39, 0x8f, 0x94, 0x7f, 0xea, 0x36, 0x47, 0xb5, 0x49, 0x77, 0x6f, 0x67, 0x7a, 0xe3,
	0x92, 0xa6, 0x33, 0xc3, 0xa1, 0x05, 0x95, 0x3c, 0x83, 0x5e, 0x96, 0x32, 0xa9, 0x99, 0x9f, 0x09,
	0x25, 0xb5, 0xdb, 0x1a, 0x35, 0x26, 0xdd, 0xbd, 0xf1, 0x9a, 0xd0, 0xe3, 0x2b, 0x2a, 0xad, 0xc4,
	0x91, 0xcf, 0xe0, 0xc1, 0x92, 0xed, 0xf9, 0x2a, 0x97, 0x99, 0xdb, 0xc6, 0xf5, 0xdd, 0x5f, 0x02,
	0x0e, 0x8c, 0x9f, 0x7c, 0x0d, 0xc3, 0x90, 0x69, 0x4f, 0x27, 0x91, 0xc8, 0x3c, 0xe6, 0x23, 0xd9,
	0xf3, 0x43, 0x26, 0x17, 0x5c, 0xbb, 0x9d, 0x51, 0x6d, 0xd2, 0xa6, 0xdb, 0x21, 0xd3, 0x47, 0x06,
	0x7f, 0x5a, 0xc0, 0x07, 0x05, 0x4a, 0xbe, 0x02, 0x77, 0x25, 0xc0, 0x3b, 0x11, 0x11, 0xf7, 0x52,
	0x7e, 0xe2, 0x02, 0x9e, 0xd5, 0x16, 0xab, 0x44, 0x3c, 0x13, 0x11, 0xa7, 0xfc, 0x64, 0xfc, 0x57,
	0x1d, 0x9a, 0xb8, 0xf3, 0x3b, 0x2b, 0xb1, 0x0d, 0x1b, 0x21, 0x17, 0x8b, 0x30, 0x43, 0x11, 0x1c,
	0x6a, 0xad, 0x55, 0x85, 0x9c, 0x6b, 0x0a, 0x4d, 0xe1, 0x9d, 0xb7, 0x04, 0x3c, 0x65, 0x4f, 0x47,
	0x2a, 0x43, 0x55, 0x1c, 0xfa, 0xa0, 0x84, 0x70, 0x31, 0xd8, 0x1a, 0x5f, 0xc0, 0xf6, 0x82, 0x4b,
	0xae, 0x85, 0xf6, 0x72, 0x29, 0x2e, 0xbc, 0x4c, 0xc4, 0x5c, 0x67, 0x2c, 0x4e, 0xdc, 0x0d, 0x0c,
	0x19, 0x58, 0xf4, 0x8d, 0x14, 0x17, 0xc7, 0x25, 0x46, 0x1e, 0xc3, 0xc0, 0xc7, 0xe4, 0x2b, 0x31,
	0x2d, 0x8c, 0x21, 0x88, 0x55, 0x23, 0x86, 0xd0, 0x4e, 0x95, 0xca, 0x3c, 0x99, 0xc7, 0x28, 0x8d,
	0x43, 0x5b, 0xc6, 0x7e, 0x95, 0xc7, 0xe3, 0xd7, 0xd0, 0x9c, 0xb1, 0xcc, 0x0f, 0xaf, 0xf5, 0x43,
	0xed, 0xff, 0xf5, 0xc3, 0x38, 0x82, 0x41, 0x55, 0xb9, 0x59, 0x2e, 0x83, 0x88, 0x93, 0xe3, 0x1b,
	0xf3, 0x3f, 0x5e, 0x93, 0xbf, 0x9a, 0xe2, 0x27, 0x9e, 0x1e, 0xa7, 0x17, 0x87, 0x32, 0xe0, 0x17,
	0x2b, 0xd5, 0x32, 0x18, 0xae, 0xa5, 0x92, 0x9f, 0xa1, 0x27, 0xa4, 0xce, 0xd2, 0xbc, 0x52, 0x72,
	0xff, 0xae, 0x25, 0x0f, 0xaf, 0x62, 0x69, 0x25, 0xd1, 0xf8, 0x57, 0xd8, 0xb9, 0x8d, 0x4d, 0xbe,
	0x83, 0x56, 0xd9, 0xd4, 0x45, 0xcd, 0x8f, 0xee, 0x52, 0x93, 0x96, 0x41, 0xe3, 0x3f, 0x1b, 0xd0,
	0x5d, 0x3a, 0xe1, 0x6b, 0x8d, 0x3b, 0x84, 0xb6, 0x69, 0x2c, 0xd4, 0xb3, 0x68, 0xdd, 0x96, 0xb1,
	0x5f, 0xe5, 0x31, 0x79, 0x08, 0x1d, 0x84, 0x42, 0xa6, 0x43, 0xfb, 0x86, 0x20, 0xf7, 0x39, 0xd3,
	0x21, 0x19, 0x40, 0x53, 0x98, 0x93, 0xc1, 0xd6, 0x75, 0x68, 0x61, 0x90, 0x7d, 0xd8, 0x62, 0x41,
	0x20, 0x4c, 0x25, 0x16, 0x79, 0x5a, 0x2c, 0x24, 0xcb, 0xf2, 0x94, 0x6b, 0xb7, 0x39, 0x6a, 0x4c,
	0x3a, 0x74, 0x70, 0x05, 0x1e, 0xbd, 0xc5, 0xc8, 0xb7, 0xe6, 0x8e, 0xb0, 0x80, 0xa7, 0xd8, 0xaa,
	0xeb, 0x77, 0xf8, 0x92, 0x6b, 0xcd, 0x16, 0xfc, 0x39, 0x72, 0xa9, 0x8d, 0x21, 0x8f, 0xa0, 0x57,
	0x5e, 0xe6, 0x53, 0x7e, 0x59, 0x3c, 0x3e, 0x1d, 0xda, 0xb5, 0xbe, 0x1f, 0xf9, 0xa5, 0x26, 0x9f,
	0xc2, 0xfd, 0x94, 0xfb, 0x5c, 0x66, 0xc5, 0x4d, 0xc2, 0xfd, 0xb4, 0x71, 0x3f, 0xf7, 0x0a, 0xff,
	0xac, 0x74, 0x9b, 0x6c, 0x91, 0x5a, 0x78, 0x71, 0x51, 0x4a, 0xbb, 0xbd, 0x22, 0x5b, 0xa4, 0x16,
	0xb6, 0xba, 0x36, 0xdd, 0x5d, 0x69, 0x85, 0xfe, 0xad, 0xdd, 0xbd, 0x5e, 0xf9, 0xbf, 0x6b, 0xd0,
	0xaf, 0x6c, 0x89, 0x7c, 0x09, 0xef, 0xca, 0x3c, 0xf6, 0x52, 0xfe, 0x5b, 0x2e, 0x52, 0x1e, 0x2c,
	0x9f, 0x5f, 0x0d, 0x5f, 0xc1, 0x2d, 0x99, 0xc7, 0xd4, 0xa2, 0x4b, 0x07, 0xf8, 0x3d, 0xec, 0x14,
	0x71, 0x2c, 0x50, 0x32, 0xba, 0xc4, 0x38, 0x1e, 0x94, 0x8f, 0xa2, 0x46, 0x5d, 0xfb, 0x74, 0x88,
	0xc1, 0x05, 0xe5, 0x08, 0x19, 0xb6, 0x65, 0x34, 0x39, 0x80, 0xf7, 0x2b, 0x09, 0x72, 0xb9, 0x9a,
	0xa2, 0x81, 0x29, 0x1e, 0x2e, 0xa5, 0x78, 0x63, 0x39, 0x65, 0x92, 0xf1, 0x3f, 0x75, 0xe8, 0x2e,
	0x77, 0xee, 0x7b, 0x00, 0x49, 0xaa, 0x16, 0x29, 0x8b, 0xaf, 0x66, 0x50, 0xc7, 0x7a, 0x0e, 0x83,
	0x6b, 0xba, 0x39, 0xd7, 0x75, 0x23, 0xe0, 0x04, 0x2c, 0x63, 0xf8, 0xe8, 0xf5, 0x28, 0x7e, 0x9b,
	0xc9, 0xa5, 0xd2, 0x40, 0x48, 0x16, 0x61, 0xb7, 0xf4, 0x69, 0x69, 0x92, 0x8f, 0x61, 0x33, 0x61,
	0xa9, 0x51, 0xb9, 0x24, 0xb4, 0x90, 0xd0, 0x2f, 0xbc, 0xaf, 0x2d, 0x6d, 0x00, 0xcd, 0x80, 0x27,
	0x59, 0x68, 0x07, 0x4b, 0x61, 0x90, 0x97, 0x70, 0x6f, 0xce, 0x22, 0x26, 0x7d, 0xbe, 0x34, 0x43,
	0x6e, 0xbb, 0x6e, 0xb3, 0x82, 0x6d, 0xaf, 0xdb, 0xe6, 0x7c, 0xd9, 0xd4, 0x26, 0xdd, 0xea, 0x48,
	0x82, 0xff, 0x70, 0x7b, 0x37, 0xab, 0xe3, 0x67, 0xac, 0xa0, 0x5f, 0xa9, 0x67, 0xc6, 0x4a, 0x92,
	0xcf, 0x4f, 0xf9, 0xa5, 0xbd, 0xc9, 0xd6, 0x22, 0x1f, 0x42, 0xdf, 0x8c, 0x06, 0x2f, 0x62, 0x71,
	0xa2, 0x52, 0x2b, 0xbd, 0x43, 0x7b, 0xc6, 0xf9, 0xc2, 0xfa, 0xcc, 0xc9, 0x4b, 0x7e, 0x7e, 0xc5,
	0x29, 0x26, 0x53, 0x57, 0xf2, 0xf3, 0x92, 0x32, 0xfe, 0xa3, 0x06, 0xfd, 0xca, 0x92, 0xd6, 0x56,
	0x7c, 0x08, 0x1d, 0xac, 0x88, 0x42, 0xd5, 0x51, 0xa8, 0xb6, 0x71, 0xfc, 0x60, 0xc4, 0x1a, 0x42,
	0xdb, 0x54, 0x42, 0xac, 0x81, 0x58, 0x4b, 0xf2, 0x73, 0x84, 0x3e, 0x81, 0x7b, 0x25, 0xe4, 0x45,
	0x5c, 0x2e, 0xb2, 0xd0, 0xbe, 0x24, 0x7d, 0xcb, 0x78, 0x81, 0xce, 0xd9, 0xc1, 0x2f, 0x4f, 0x17,
	0x22, 0x0b, 0xf3, 0xf9, 0xd4, 0x57, 0xf1, 0x2e, 0x1e, 0xde, 0xe7, 0x42, 0xd9, 0x0f, 0xfb, 0x2f,
	0x95, 0xcc, 0x77, 0x6f, 0xfc, 0xb7, 0xfa, 0x26, 0x99, 0xe3, 0xe7, 0x7c, 0x03, 0x7f, 0xaf, 0xf6,
	0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x1b, 0xa4, 0xa6, 0x69, 0x83, 0x09, 0x00, 0x00,
}
