// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dfuse/solana/serumhist/v1/serumhist.proto

package pbserumhist

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Side int32

const (
	Side_BID Side = 0
	Side_ASK Side = 1
)

var Side_name = map[int32]string{
	0: "BID",
	1: "ASK",
}

var Side_value = map[string]int32{
	"BID": 0,
	"ASK": 1,
}

func (x Side) String() string {
	return proto.EnumName(Side_name, int32(x))
}

func (Side) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c18832c9aa9279e6, []int{0}
}

type FeeTier int32

const (
	FeeTier_Base FeeTier = 0
	FeeTier_SRM2 FeeTier = 1
	FeeTier_SRM3 FeeTier = 2
	FeeTier_SRM4 FeeTier = 3
	FeeTier_SRM5 FeeTier = 4
	FeeTier_SRM6 FeeTier = 5
	FeeTier_MSRM FeeTier = 6
)

var FeeTier_name = map[int32]string{
	0: "Base",
	1: "SRM2",
	2: "SRM3",
	3: "SRM4",
	4: "SRM5",
	5: "SRM6",
	6: "MSRM",
}

var FeeTier_value = map[string]int32{
	"Base": 0,
	"SRM2": 1,
	"SRM3": 2,
	"SRM4": 3,
	"SRM5": 4,
	"SRM6": 5,
	"MSRM": 6,
}

func (x FeeTier) String() string {
	return proto.EnumName(FeeTier_name, int32(x))
}

func (FeeTier) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c18832c9aa9279e6, []int{1}
}

type OrderType int32

const (
	OrderType_LIMIT               OrderType = 0
	OrderType_IMMEDIATE_OR_CANCEL OrderType = 1
	OrderType_POST_ONLY           OrderType = 2
)

var OrderType_name = map[int32]string{
	0: "LIMIT",
	1: "IMMEDIATE_OR_CANCEL",
	2: "POST_ONLY",
}

var OrderType_value = map[string]int32{
	"LIMIT":               0,
	"IMMEDIATE_OR_CANCEL": 1,
	"POST_ONLY":           2,
}

func (x OrderType) String() string {
	return proto.EnumName(OrderType_name, int32(x))
}

func (OrderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c18832c9aa9279e6, []int{2}
}

type OrderTransition_State int32

const (
	OrderTransition_STATE_UNKNOWN        OrderTransition_State = 0
	OrderTransition_STATE_APPROVED       OrderTransition_State = 1
	OrderTransition_STATE_CANCEL_PENDING OrderTransition_State = 2
	OrderTransition_STATE_CANCELLED      OrderTransition_State = 3
	OrderTransition_STATE_PARTIAL        OrderTransition_State = 4
	OrderTransition_STATE_EXECUTED       OrderTransition_State = 5
)

var OrderTransition_State_name = map[int32]string{
	0: "STATE_UNKNOWN",
	1: "STATE_APPROVED",
	2: "STATE_CANCEL_PENDING",
	3: "STATE_CANCELLED",
	4: "STATE_PARTIAL",
	5: "STATE_EXECUTED",
}

var OrderTransition_State_value = map[string]int32{
	"STATE_UNKNOWN":        0,
	"STATE_APPROVED":       1,
	"STATE_CANCEL_PENDING": 2,
	"STATE_CANCELLED":      3,
	"STATE_PARTIAL":        4,
	"STATE_EXECUTED":       5,
}

func (x OrderTransition_State) String() string {
	return proto.EnumName(OrderTransition_State_name, int32(x))
}

func (OrderTransition_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c18832c9aa9279e6, []int{3, 0}
}

type OrderTransition_Transition int32

const (
	OrderTransition_TRANS_INIT                 OrderTransition_Transition = 0
	OrderTransition_TRANS_ACCEPTED             OrderTransition_Transition = 1
	OrderTransition_TRANS_PENDING_CANCELLATION OrderTransition_Transition = 2
	OrderTransition_TRANS_CANCELLED            OrderTransition_Transition = 3
	OrderTransition_TRANS_FILLED               OrderTransition_Transition = 4
	OrderTransition_TRANS_EXECUTED             OrderTransition_Transition = 5
)

var OrderTransition_Transition_name = map[int32]string{
	0: "TRANS_INIT",
	1: "TRANS_ACCEPTED",
	2: "TRANS_PENDING_CANCELLATION",
	3: "TRANS_CANCELLED",
	4: "TRANS_FILLED",
	5: "TRANS_EXECUTED",
}

var OrderTransition_Transition_value = map[string]int32{
	"TRANS_INIT":                 0,
	"TRANS_ACCEPTED":             1,
	"TRANS_PENDING_CANCELLATION": 2,
	"TRANS_CANCELLED":            3,
	"TRANS_FILLED":               4,
	"TRANS_EXECUTED":             5,
}

func (x OrderTransition_Transition) String() string {
	return proto.EnumName(OrderTransition_Transition_name, int32(x))
}

func (OrderTransition_Transition) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c18832c9aa9279e6, []int{3, 1}
}

type GetFillsRequest struct {
	Trader               string   `protobuf:"bytes,1,opt,name=trader,proto3" json:"trader,omitempty"`
	Market               string   `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFillsRequest) Reset()         { *m = GetFillsRequest{} }
func (m *GetFillsRequest) String() string { return proto.CompactTextString(m) }
func (*GetFillsRequest) ProtoMessage()    {}
func (*GetFillsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c18832c9aa9279e6, []int{0}
}

func (m *GetFillsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFillsRequest.Unmarshal(m, b)
}
func (m *GetFillsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFillsRequest.Marshal(b, m, deterministic)
}
func (m *GetFillsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFillsRequest.Merge(m, src)
}
func (m *GetFillsRequest) XXX_Size() int {
	return xxx_messageInfo_GetFillsRequest.Size(m)
}
func (m *GetFillsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFillsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFillsRequest proto.InternalMessageInfo

func (m *GetFillsRequest) GetTrader() string {
	if m != nil {
		return m.Trader
	}
	return ""
}

func (m *GetFillsRequest) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

type FillsResponse struct {
	Fill                 []*Fill  `protobuf:"bytes,1,rep,name=fill,proto3" json:"fill,omitempty"`
	HasMore              bool     `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FillsResponse) Reset()         { *m = FillsResponse{} }
func (m *FillsResponse) String() string { return proto.CompactTextString(m) }
func (*FillsResponse) ProtoMessage()    {}
func (*FillsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c18832c9aa9279e6, []int{1}
}

func (m *FillsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FillsResponse.Unmarshal(m, b)
}
func (m *FillsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FillsResponse.Marshal(b, m, deterministic)
}
func (m *FillsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FillsResponse.Merge(m, src)
}
func (m *FillsResponse) XXX_Size() int {
	return xxx_messageInfo_FillsResponse.Size(m)
}
func (m *FillsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FillsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FillsResponse proto.InternalMessageInfo

func (m *FillsResponse) GetFill() []*Fill {
	if m != nil {
		return m.Fill
	}
	return nil
}

func (m *FillsResponse) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

type TrackOrderRequest struct {
	Market               string   `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	OrderId              uint64   `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackOrderRequest) Reset()         { *m = TrackOrderRequest{} }
func (m *TrackOrderRequest) String() string { return proto.CompactTextString(m) }
func (*TrackOrderRequest) ProtoMessage()    {}
func (*TrackOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c18832c9aa9279e6, []int{2}
}

func (m *TrackOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackOrderRequest.Unmarshal(m, b)
}
func (m *TrackOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackOrderRequest.Marshal(b, m, deterministic)
}
func (m *TrackOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackOrderRequest.Merge(m, src)
}
func (m *TrackOrderRequest) XXX_Size() int {
	return xxx_messageInfo_TrackOrderRequest.Size(m)
}
func (m *TrackOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TrackOrderRequest proto.InternalMessageInfo

func (m *TrackOrderRequest) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *TrackOrderRequest) GetOrderId() uint64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

type OrderTransition struct {
	PreviousState        OrderTransition_State      `protobuf:"varint,1,opt,name=previous_state,json=previousState,proto3,enum=dfuse.solana.serumhist.v1.OrderTransition_State" json:"previous_state,omitempty"`
	CurrentState         OrderTransition_State      `protobuf:"varint,2,opt,name=current_state,json=currentState,proto3,enum=dfuse.solana.serumhist.v1.OrderTransition_State" json:"current_state,omitempty"`
	Transition           OrderTransition_Transition `protobuf:"varint,3,opt,name=transition,proto3,enum=dfuse.solana.serumhist.v1.OrderTransition_Transition" json:"transition,omitempty"`
	Order                *Order                     `protobuf:"bytes,4,opt,name=order,proto3" json:"order,omitempty"`
	AddedFill            *Fill                      `protobuf:"bytes,5,opt,name=added_fill,json=addedFill,proto3" json:"added_fill,omitempty"`
	Cancellation         *SerumTemporal             `protobuf:"bytes,6,opt,name=cancellation,proto3" json:"cancellation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *OrderTransition) Reset()         { *m = OrderTransition{} }
func (m *OrderTransition) String() string { return proto.CompactTextString(m) }
func (*OrderTransition) ProtoMessage()    {}
func (*OrderTransition) Descriptor() ([]byte, []int) {
	return fileDescriptor_c18832c9aa9279e6, []int{3}
}

func (m *OrderTransition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderTransition.Unmarshal(m, b)
}
func (m *OrderTransition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderTransition.Marshal(b, m, deterministic)
}
func (m *OrderTransition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderTransition.Merge(m, src)
}
func (m *OrderTransition) XXX_Size() int {
	return xxx_messageInfo_OrderTransition.Size(m)
}
func (m *OrderTransition) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderTransition.DiscardUnknown(m)
}

var xxx_messageInfo_OrderTransition proto.InternalMessageInfo

func (m *OrderTransition) GetPreviousState() OrderTransition_State {
	if m != nil {
		return m.PreviousState
	}
	return OrderTransition_STATE_UNKNOWN
}

func (m *OrderTransition) GetCurrentState() OrderTransition_State {
	if m != nil {
		return m.CurrentState
	}
	return OrderTransition_STATE_UNKNOWN
}

func (m *OrderTransition) GetTransition() OrderTransition_Transition {
	if m != nil {
		return m.Transition
	}
	return OrderTransition_TRANS_INIT
}

func (m *OrderTransition) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *OrderTransition) GetAddedFill() *Fill {
	if m != nil {
		return m.AddedFill
	}
	return nil
}

func (m *OrderTransition) GetCancellation() *SerumTemporal {
	if m != nil {
		return m.Cancellation
	}
	return nil
}

type SerumTemporal struct {
	SlotNum              uint64               `protobuf:"varint,1,opt,name=slot_num,json=slotNum,proto3" json:"slot_num,omitempty"`
	TrxHash              string               `protobuf:"bytes,2,opt,name=trx_hash,json=trxHash,proto3" json:"trx_hash,omitempty"`
	TrxIdx               uint32               `protobuf:"varint,3,opt,name=trx_idx,json=trxIdx,proto3" json:"trx_idx,omitempty"`
	InstIdx              uint32               `protobuf:"varint,4,opt,name=inst_idx,json=instIdx,proto3" json:"inst_idx,omitempty"`
	SlotHash             string               `protobuf:"bytes,5,opt,name=slot_hash,json=slotHash,proto3" json:"slot_hash,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SerumTemporal) Reset()         { *m = SerumTemporal{} }
func (m *SerumTemporal) String() string { return proto.CompactTextString(m) }
func (*SerumTemporal) ProtoMessage()    {}
func (*SerumTemporal) Descriptor() ([]byte, []int) {
	return fileDescriptor_c18832c9aa9279e6, []int{4}
}

func (m *SerumTemporal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SerumTemporal.Unmarshal(m, b)
}
func (m *SerumTemporal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SerumTemporal.Marshal(b, m, deterministic)
}
func (m *SerumTemporal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SerumTemporal.Merge(m, src)
}
func (m *SerumTemporal) XXX_Size() int {
	return xxx_messageInfo_SerumTemporal.Size(m)
}
func (m *SerumTemporal) XXX_DiscardUnknown() {
	xxx_messageInfo_SerumTemporal.DiscardUnknown(m)
}

var xxx_messageInfo_SerumTemporal proto.InternalMessageInfo

func (m *SerumTemporal) GetSlotNum() uint64 {
	if m != nil {
		return m.SlotNum
	}
	return 0
}

func (m *SerumTemporal) GetTrxHash() string {
	if m != nil {
		return m.TrxHash
	}
	return ""
}

func (m *SerumTemporal) GetTrxIdx() uint32 {
	if m != nil {
		return m.TrxIdx
	}
	return 0
}

func (m *SerumTemporal) GetInstIdx() uint32 {
	if m != nil {
		return m.InstIdx
	}
	return 0
}

func (m *SerumTemporal) GetSlotHash() string {
	if m != nil {
		return m.SlotHash
	}
	return ""
}

func (m *SerumTemporal) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type Checkpoint struct {
	LastWrittenSlotNum   uint64   `protobuf:"varint,1,opt,name=last_written_slot_num,json=lastWrittenSlotNum,proto3" json:"last_written_slot_num,omitempty"`
	LastWrittenSlotId    string   `protobuf:"bytes,2,opt,name=last_written_slot_id,json=lastWrittenSlotId,proto3" json:"last_written_slot_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Checkpoint) Reset()         { *m = Checkpoint{} }
func (m *Checkpoint) String() string { return proto.CompactTextString(m) }
func (*Checkpoint) ProtoMessage()    {}
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_c18832c9aa9279e6, []int{5}
}

func (m *Checkpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Checkpoint.Unmarshal(m, b)
}
func (m *Checkpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Checkpoint.Marshal(b, m, deterministic)
}
func (m *Checkpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Checkpoint.Merge(m, src)
}
func (m *Checkpoint) XXX_Size() int {
	return xxx_messageInfo_Checkpoint.Size(m)
}
func (m *Checkpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Checkpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Checkpoint proto.InternalMessageInfo

func (m *Checkpoint) GetLastWrittenSlotNum() uint64 {
	if m != nil {
		return m.LastWrittenSlotNum
	}
	return 0
}

func (m *Checkpoint) GetLastWrittenSlotId() string {
	if m != nil {
		return m.LastWrittenSlotId
	}
	return ""
}

type Fill struct {
	Trader               string               `protobuf:"bytes,1,opt,name=trader,proto3" json:"trader,omitempty"`
	Market               string               `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	OrderId              string               `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Side                 Side                 `protobuf:"varint,4,opt,name=side,proto3,enum=dfuse.solana.serumhist.v1.Side" json:"side,omitempty"`
	Maker                bool                 `protobuf:"varint,5,opt,name=maker,proto3" json:"maker,omitempty"`
	NativeQtyPaid        uint64               `protobuf:"varint,6,opt,name=native_qty_paid,json=nativeQtyPaid,proto3" json:"native_qty_paid,omitempty"`
	NativeQtyReceived    uint64               `protobuf:"varint,7,opt,name=native_qty_received,json=nativeQtyReceived,proto3" json:"native_qty_received,omitempty"`
	NativeFeeOrRebate    uint64               `protobuf:"varint,8,opt,name=native_fee_or_rebate,json=nativeFeeOrRebate,proto3" json:"native_fee_or_rebate,omitempty"`
	FeeTier              FeeTier              `protobuf:"varint,9,opt,name=fee_tier,json=feeTier,proto3,enum=dfuse.solana.serumhist.v1.FeeTier" json:"fee_tier,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SlotNum              uint64               `protobuf:"varint,20,opt,name=slot_num,json=slotNum,proto3" json:"slot_num,omitempty"`
	SlotHash             string               `protobuf:"bytes,24,opt,name=slot_hash,json=slotHash,proto3" json:"slot_hash,omitempty"`
	TrxId                string               `protobuf:"bytes,25,opt,name=trx_id,json=trxId,proto3" json:"trx_id,omitempty"`
	TrxIdx               uint32               `protobuf:"varint,21,opt,name=trx_idx,json=trxIdx,proto3" json:"trx_idx,omitempty"`
	InstIdx              uint32               `protobuf:"varint,22,opt,name=inst_idx,json=instIdx,proto3" json:"inst_idx,omitempty"`
	OrderSeqNum          uint64               `protobuf:"varint,23,opt,name=order_seq_num,json=orderSeqNum,proto3" json:"order_seq_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Fill) Reset()         { *m = Fill{} }
func (m *Fill) String() string { return proto.CompactTextString(m) }
func (*Fill) ProtoMessage()    {}
func (*Fill) Descriptor() ([]byte, []int) {
	return fileDescriptor_c18832c9aa9279e6, []int{6}
}

func (m *Fill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fill.Unmarshal(m, b)
}
func (m *Fill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fill.Marshal(b, m, deterministic)
}
func (m *Fill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fill.Merge(m, src)
}
func (m *Fill) XXX_Size() int {
	return xxx_messageInfo_Fill.Size(m)
}
func (m *Fill) XXX_DiscardUnknown() {
	xxx_messageInfo_Fill.DiscardUnknown(m)
}

var xxx_messageInfo_Fill proto.InternalMessageInfo

func (m *Fill) GetTrader() string {
	if m != nil {
		return m.Trader
	}
	return ""
}

func (m *Fill) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *Fill) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *Fill) GetSide() Side {
	if m != nil {
		return m.Side
	}
	return Side_BID
}

func (m *Fill) GetMaker() bool {
	if m != nil {
		return m.Maker
	}
	return false
}

func (m *Fill) GetNativeQtyPaid() uint64 {
	if m != nil {
		return m.NativeQtyPaid
	}
	return 0
}

func (m *Fill) GetNativeQtyReceived() uint64 {
	if m != nil {
		return m.NativeQtyReceived
	}
	return 0
}

func (m *Fill) GetNativeFeeOrRebate() uint64 {
	if m != nil {
		return m.NativeFeeOrRebate
	}
	return 0
}

func (m *Fill) GetFeeTier() FeeTier {
	if m != nil {
		return m.FeeTier
	}
	return FeeTier_Base
}

func (m *Fill) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Fill) GetSlotNum() uint64 {
	if m != nil {
		return m.SlotNum
	}
	return 0
}

func (m *Fill) GetSlotHash() string {
	if m != nil {
		return m.SlotHash
	}
	return ""
}

func (m *Fill) GetTrxId() string {
	if m != nil {
		return m.TrxId
	}
	return ""
}

func (m *Fill) GetTrxIdx() uint32 {
	if m != nil {
		return m.TrxIdx
	}
	return 0
}

func (m *Fill) GetInstIdx() uint32 {
	if m != nil {
		return m.InstIdx
	}
	return 0
}

func (m *Fill) GetOrderSeqNum() uint64 {
	if m != nil {
		return m.OrderSeqNum
	}
	return 0
}

type Order struct {
	Num                  uint64    `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Market               string    `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	Trader               string    `protobuf:"bytes,3,opt,name=trader,proto3" json:"trader,omitempty"`
	Side                 Side      `protobuf:"varint,4,opt,name=side,proto3,enum=dfuse.solana.serumhist.v1.Side" json:"side,omitempty"`
	LimitPrice           uint64    `protobuf:"varint,5,opt,name=limit_price,json=limitPrice,proto3" json:"limit_price,omitempty"`
	MaxQuantity          uint64    `protobuf:"varint,6,opt,name=max_quantity,json=maxQuantity,proto3" json:"max_quantity,omitempty"`
	Type                 OrderType `protobuf:"varint,7,opt,name=type,proto3,enum=dfuse.solana.serumhist.v1.OrderType" json:"type,omitempty"`
	Fills                []*Fill   `protobuf:"bytes,10,rep,name=fills,proto3" json:"fills,omitempty"`
	SlotNum              uint64    `protobuf:"varint,20,opt,name=slot_num,json=slotNum,proto3" json:"slot_num,omitempty"`
	SlotHash             string    `protobuf:"bytes,24,opt,name=slot_hash,json=slotHash,proto3" json:"slot_hash,omitempty"`
	TrxId                string    `protobuf:"bytes,25,opt,name=trx_id,json=trxId,proto3" json:"trx_id,omitempty"`
	TrxIdx               uint32    `protobuf:"varint,21,opt,name=trx_idx,json=trxIdx,proto3" json:"trx_idx,omitempty"`
	InstIdx              uint32    `protobuf:"varint,22,opt,name=inst_idx,json=instIdx,proto3" json:"inst_idx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_c18832c9aa9279e6, []int{7}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetNum() uint64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *Order) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *Order) GetTrader() string {
	if m != nil {
		return m.Trader
	}
	return ""
}

func (m *Order) GetSide() Side {
	if m != nil {
		return m.Side
	}
	return Side_BID
}

func (m *Order) GetLimitPrice() uint64 {
	if m != nil {
		return m.LimitPrice
	}
	return 0
}

func (m *Order) GetMaxQuantity() uint64 {
	if m != nil {
		return m.MaxQuantity
	}
	return 0
}

func (m *Order) GetType() OrderType {
	if m != nil {
		return m.Type
	}
	return OrderType_LIMIT
}

func (m *Order) GetFills() []*Fill {
	if m != nil {
		return m.Fills
	}
	return nil
}

func (m *Order) GetSlotNum() uint64 {
	if m != nil {
		return m.SlotNum
	}
	return 0
}

func (m *Order) GetSlotHash() string {
	if m != nil {
		return m.SlotHash
	}
	return ""
}

func (m *Order) GetTrxId() string {
	if m != nil {
		return m.TrxId
	}
	return ""
}

func (m *Order) GetTrxIdx() uint32 {
	if m != nil {
		return m.TrxIdx
	}
	return 0
}

func (m *Order) GetInstIdx() uint32 {
	if m != nil {
		return m.InstIdx
	}
	return 0
}

func init() {
	proto.RegisterEnum("dfuse.solana.serumhist.v1.Side", Side_name, Side_value)
	proto.RegisterEnum("dfuse.solana.serumhist.v1.FeeTier", FeeTier_name, FeeTier_value)
	proto.RegisterEnum("dfuse.solana.serumhist.v1.OrderType", OrderType_name, OrderType_value)
	proto.RegisterEnum("dfuse.solana.serumhist.v1.OrderTransition_State", OrderTransition_State_name, OrderTransition_State_value)
	proto.RegisterEnum("dfuse.solana.serumhist.v1.OrderTransition_Transition", OrderTransition_Transition_name, OrderTransition_Transition_value)
	proto.RegisterType((*GetFillsRequest)(nil), "dfuse.solana.serumhist.v1.GetFillsRequest")
	proto.RegisterType((*FillsResponse)(nil), "dfuse.solana.serumhist.v1.FillsResponse")
	proto.RegisterType((*TrackOrderRequest)(nil), "dfuse.solana.serumhist.v1.TrackOrderRequest")
	proto.RegisterType((*OrderTransition)(nil), "dfuse.solana.serumhist.v1.OrderTransition")
	proto.RegisterType((*SerumTemporal)(nil), "dfuse.solana.serumhist.v1.SerumTemporal")
	proto.RegisterType((*Checkpoint)(nil), "dfuse.solana.serumhist.v1.Checkpoint")
	proto.RegisterType((*Fill)(nil), "dfuse.solana.serumhist.v1.Fill")
	proto.RegisterType((*Order)(nil), "dfuse.solana.serumhist.v1.Order")
}

func init() {
	proto.RegisterFile("dfuse/solana/serumhist/v1/serumhist.proto", fileDescriptor_c18832c9aa9279e6)
}

var fileDescriptor_c18832c9aa9279e6 = []byte{
	// 1198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x0e, 0x2d, 0xca, 0x92, 0xc6, 0x96, 0x4d, 0x6f, 0x9c, 0x44, 0x71, 0x81, 0xc6, 0x15, 0x8a,
	0xc2, 0x35, 0x5a, 0x29, 0x51, 0x9a, 0x20, 0x40, 0xd1, 0x00, 0x8a, 0x2d, 0x27, 0x44, 0xac, 0x9f,
	0xac, 0x98, 0xa6, 0xed, 0x85, 0x5d, 0x8b, 0xeb, 0x68, 0x61, 0x51, 0xa4, 0x97, 0x2b, 0x57, 0x3e,
	0xf4, 0xd6, 0x5b, 0xdf, 0xa7, 0x6f, 0xd0, 0x7b, 0xdf, 0xa5, 0x2f, 0x50, 0xec, 0x70, 0x65, 0x49,
	0x0e, 0x2c, 0xc7, 0x39, 0xf5, 0x36, 0xbf, 0x1f, 0x67, 0x67, 0x3f, 0xce, 0x0e, 0x7c, 0x1d, 0x1c,
	0x8f, 0x12, 0x5e, 0x4d, 0xa2, 0x01, 0x1b, 0xb2, 0x6a, 0xc2, 0xe5, 0x28, 0xec, 0x8b, 0x44, 0x55,
	0xcf, 0x1e, 0x4d, 0x95, 0x4a, 0x2c, 0x23, 0x15, 0x91, 0xfb, 0x18, 0x5a, 0x49, 0x43, 0x2b, 0x53,
	0xef, 0xd9, 0xa3, 0xad, 0x07, 0xef, 0xa3, 0xe8, 0xfd, 0x80, 0x57, 0x31, 0xf0, 0x68, 0x74, 0x5c,
	0x55, 0x22, 0xe4, 0x89, 0x62, 0x61, 0x9c, 0xe6, 0x96, 0xeb, 0xb0, 0xfe, 0x92, 0xab, 0x03, 0x31,
	0x18, 0x24, 0x94, 0x9f, 0x8e, 0x78, 0xa2, 0xc8, 0x5d, 0x58, 0x56, 0x92, 0x05, 0x5c, 0x96, 0xac,
	0x6d, 0x6b, 0xa7, 0x40, 0x8d, 0xa6, 0xed, 0x21, 0x93, 0x27, 0x5c, 0x95, 0x96, 0x52, 0x7b, 0xaa,
	0x95, 0x7d, 0x28, 0x9a, 0xfc, 0x24, 0x8e, 0x86, 0x09, 0x27, 0x8f, 0xc1, 0x3e, 0x16, 0x83, 0x41,
	0xc9, 0xda, 0xce, 0xec, 0xac, 0xd4, 0x1e, 0x54, 0xae, 0x2c, 0xaf, 0xa2, 0xf3, 0x28, 0x06, 0x93,
	0xfb, 0x90, 0xef, 0xb3, 0xc4, 0x0f, 0x23, 0xc9, 0x11, 0x3f, 0x4f, 0x73, 0x7d, 0x96, 0x34, 0x23,
	0xc9, 0xcb, 0x07, 0xb0, 0xe1, 0x49, 0xd6, 0x3b, 0x69, 0xcb, 0x80, 0xcb, 0x99, 0x2a, 0x4d, 0x35,
	0xd6, 0x6c, 0x35, 0x1a, 0x27, 0xd2, 0x71, 0xbe, 0x08, 0x10, 0xc7, 0xa6, 0x39, 0xd4, 0xdd, 0xa0,
	0xfc, 0x6f, 0x16, 0xd6, 0x11, 0xc3, 0x93, 0x6c, 0x98, 0x08, 0x25, 0xa2, 0x21, 0x79, 0x07, 0x6b,
	0xb1, 0xe4, 0x67, 0x22, 0x1a, 0x25, 0x7e, 0xa2, 0x98, 0xe2, 0x08, 0xb7, 0x56, 0x7b, 0xb8, 0xa0,
	0xea, 0x4b, 0x18, 0x95, 0xae, 0xce, 0xa3, 0xc5, 0x09, 0x0e, 0xaa, 0xe4, 0x2d, 0x14, 0x7b, 0x23,
	0x29, 0xf9, 0x50, 0x19, 0xdc, 0xa5, 0x4f, 0xc4, 0x5d, 0x35, 0x30, 0x13, 0x58, 0x50, 0x17, 0x11,
	0xa5, 0x0c, 0x62, 0x3e, 0xb9, 0x01, 0xe6, 0x54, 0xa4, 0x33, 0x40, 0xe4, 0x29, 0x64, 0xb1, 0x4b,
	0x25, 0x7b, 0xdb, 0xda, 0x59, 0xa9, 0x6d, 0x5f, 0x87, 0x48, 0xd3, 0x70, 0xf2, 0x1c, 0x80, 0x05,
	0x01, 0x0f, 0x7c, 0xbc, 0xf0, 0x2c, 0x26, 0x5f, 0x7b, 0xe1, 0x05, 0x4c, 0xd1, 0x22, 0x39, 0x84,
	0xd5, 0x1e, 0x1b, 0xf6, 0xf8, 0x60, 0xc0, 0xf0, 0x40, 0xcb, 0x88, 0xb0, 0xb3, 0x00, 0xa1, 0xab,
	0x15, 0x8f, 0x87, 0x71, 0x24, 0xd9, 0x80, 0xce, 0x65, 0x97, 0xff, 0xb0, 0x20, 0x9b, 0xb6, 0x69,
	0x03, 0x8a, 0x5d, 0xaf, 0xee, 0x35, 0xfc, 0xb7, 0xad, 0xd7, 0xad, 0xf6, 0xbb, 0x96, 0x73, 0x8b,
	0x10, 0x58, 0x4b, 0x4d, 0xf5, 0x4e, 0x87, 0xb6, 0x7f, 0x6c, 0xec, 0x3b, 0x16, 0x29, 0xc1, 0x66,
	0x6a, 0xdb, 0xab, 0xb7, 0xf6, 0x1a, 0x87, 0x7e, 0xa7, 0xd1, 0xda, 0x77, 0x5b, 0x2f, 0x9d, 0x25,
	0x72, 0x1b, 0xd6, 0x67, 0x3d, 0x87, 0x8d, 0x7d, 0x27, 0x33, 0x45, 0xed, 0xd4, 0xa9, 0xe7, 0xd6,
	0x0f, 0x1d, 0x7b, 0x8a, 0xda, 0xf8, 0xa9, 0xb1, 0xf7, 0xd6, 0x6b, 0xec, 0x3b, 0xd9, 0xf2, 0x9f,
	0x16, 0xc0, 0x0c, 0xc5, 0xd6, 0x00, 0x3c, 0x5a, 0x6f, 0x75, 0x7d, 0xb7, 0xe5, 0x7a, 0x69, 0x21,
	0xa9, 0x5e, 0xdf, 0xdb, 0x6b, 0x74, 0x3c, 0x2c, 0xe4, 0x73, 0xd8, 0x4a, 0x6d, 0xa6, 0x82, 0xc9,
	0x67, 0xeb, 0x9e, 0xdb, 0x6e, 0xa5, 0xe5, 0xa4, 0xfe, 0xd9, 0x72, 0x1c, 0x58, 0x4d, 0x8d, 0x07,
	0x2e, 0x5a, 0xec, 0x29, 0xf4, 0x4c, 0x35, 0xff, 0x58, 0x50, 0x9c, 0x6b, 0x9a, 0xfe, 0x45, 0x92,
	0x41, 0xa4, 0xfc, 0xe1, 0x28, 0x44, 0xb6, 0xdb, 0x34, 0xa7, 0xf5, 0xd6, 0x28, 0xd4, 0x2e, 0x25,
	0xc7, 0x7e, 0x9f, 0x25, 0x7d, 0xf3, 0x97, 0xe7, 0x94, 0x1c, 0xbf, 0x62, 0x49, 0x9f, 0xdc, 0x03,
	0x2d, 0xfa, 0x22, 0x18, 0x23, 0xed, 0x8a, 0x7a, 0x2e, 0x8c, 0xdd, 0x60, 0xac, 0x73, 0xc4, 0x30,
	0x51, 0xe8, 0xb1, 0xd1, 0x93, 0xd3, 0xba, 0x76, 0x7d, 0x06, 0x05, 0xfc, 0x12, 0xe2, 0x65, 0x11,
	0x0f, 0x3f, 0x8d, 0x80, 0xcf, 0xa0, 0x70, 0x31, 0x8d, 0xcc, 0xc5, 0x6f, 0x55, 0xd2, 0x79, 0x55,
	0x99, 0xcc, 0xab, 0x8a, 0x37, 0x89, 0xa0, 0xd3, 0xe0, 0x72, 0x0c, 0xb0, 0xd7, 0xe7, 0xbd, 0x93,
	0x38, 0x12, 0x43, 0x45, 0x1e, 0xc1, 0x9d, 0x01, 0x4b, 0x94, 0xff, 0x9b, 0x14, 0x4a, 0xf1, 0xa1,
	0x7f, 0xe9, 0x6c, 0x44, 0x3b, 0xdf, 0xa5, 0xbe, 0xae, 0x39, 0x66, 0x15, 0x36, 0x3f, 0x4c, 0x31,
	0x03, 0xa3, 0x40, 0x37, 0x2e, 0x65, 0xb8, 0x41, 0xf9, 0x6f, 0x1b, 0x6c, 0x24, 0xec, 0x0d, 0x87,
	0xe3, 0xdc, 0x38, 0xca, 0xa4, 0x0d, 0x35, 0xe3, 0x48, 0x8f, 0xc9, 0x44, 0x04, 0x1c, 0x7b, 0xb6,
	0xb6, 0xf0, 0xaf, 0xe9, 0x8a, 0x80, 0x53, 0x0c, 0x26, 0x9b, 0x90, 0x0d, 0xd9, 0x09, 0x97, 0xd8,
	0xcd, 0x3c, 0x4d, 0x15, 0xf2, 0x15, 0xac, 0x0f, 0x99, 0x12, 0x67, 0xdc, 0x3f, 0x55, 0xe7, 0x7e,
	0xcc, 0x44, 0x80, 0x0d, 0xb5, 0x69, 0x31, 0x35, 0xbf, 0x51, 0xe7, 0x1d, 0x26, 0x02, 0x52, 0x81,
	0xdb, 0x33, 0x71, 0x92, 0xf7, 0xb8, 0x38, 0xe3, 0x41, 0x29, 0x87, 0xb1, 0x1b, 0x17, 0xb1, 0xd4,
	0x38, 0x74, 0x9f, 0x4c, 0xfc, 0x31, 0xe7, 0x7e, 0x24, 0x7d, 0xc9, 0x8f, 0xf4, 0x2c, 0xcb, 0xcf,
	0x26, 0x1c, 0x70, 0xde, 0x96, 0x14, 0x1d, 0xe4, 0x07, 0xc8, 0xeb, 0x48, 0x25, 0xb8, 0x2c, 0x15,
	0xf0, 0x5c, 0xe5, 0x45, 0xd3, 0x80, 0x73, 0x4f, 0x70, 0x49, 0x73, 0xc7, 0xa9, 0x30, 0x4f, 0x09,
	0xb8, 0x01, 0x25, 0xe6, 0x38, 0xbd, 0x39, 0xcf, 0xe9, 0x39, 0x12, 0x96, 0x2e, 0x91, 0xf0, 0x8e,
	0xbe, 0x4f, 0xcd, 0xea, 0xd2, 0x7d, 0xf4, 0x64, 0x91, 0xd4, 0xb3, 0x64, 0xbf, 0x73, 0x25, 0xd9,
	0xef, 0xce, 0x93, 0xbd, 0x0c, 0xc5, 0xf4, 0xaa, 0x13, 0x7e, 0x8a, 0x75, 0xdc, 0xc3, 0x3a, 0x56,
	0xd0, 0xd8, 0xe5, 0xa7, 0xad, 0x51, 0x58, 0xfe, 0x2b, 0x03, 0x59, 0x1c, 0xa0, 0xc4, 0x81, 0xcc,
	0x94, 0xa3, 0x5a, 0xbc, 0x92, 0x42, 0x53, 0xca, 0x65, 0xe6, 0x28, 0xf7, 0x49, 0xfc, 0x79, 0x00,
	0x2b, 0x03, 0x11, 0x0a, 0xe5, 0xc7, 0x52, 0xf4, 0x38, 0xb2, 0xc8, 0xa6, 0x80, 0xa6, 0x8e, 0xb6,
	0x90, 0x2f, 0x60, 0x35, 0x64, 0x63, 0xff, 0x74, 0xc4, 0x86, 0x4a, 0xa8, 0x73, 0xc3, 0xa3, 0x95,
	0x90, 0x8d, 0xdf, 0x18, 0x13, 0x79, 0x06, 0xb6, 0x3a, 0x8f, 0x39, 0xd2, 0x66, 0xad, 0xf6, 0xe5,
	0xb5, 0xaf, 0xcf, 0x79, 0xcc, 0x29, 0x66, 0x90, 0x27, 0x90, 0xd5, 0x0f, 0x45, 0x52, 0x82, 0x8f,
	0x5b, 0x0d, 0xd2, 0xe8, 0xff, 0xc1, 0xe5, 0xee, 0x96, 0xc0, 0xd6, 0x5d, 0x24, 0x39, 0xc8, 0xbc,
	0x70, 0xf7, 0x9d, 0x5b, 0x5a, 0xa8, 0x77, 0x5f, 0x3b, 0xd6, 0x6e, 0x1b, 0x72, 0x86, 0xc7, 0x24,
	0x0f, 0xf6, 0x0b, 0x96, 0x70, 0xe7, 0x96, 0x96, 0xba, 0xb4, 0x59, 0x73, 0x2c, 0x23, 0x3d, 0x76,
	0x96, 0x8c, 0xf4, 0x9d, 0x93, 0x31, 0xd2, 0x13, 0xc7, 0x36, 0xd2, 0x53, 0x27, 0xab, 0xa5, 0x66,
	0x97, 0x36, 0x9d, 0xe5, 0xdd, 0xe7, 0x50, 0xb8, 0xe8, 0x1b, 0x29, 0x40, 0xf6, 0xd0, 0x6d, 0xe2,
	0xbb, 0x71, 0x0f, 0x6e, 0xbb, 0xcd, 0x66, 0x63, 0xdf, 0xd5, 0xcf, 0x4d, 0x9b, 0x9a, 0xa7, 0xc0,
	0xb1, 0x48, 0x11, 0x0a, 0x9d, 0x76, 0xd7, 0xf3, 0xdb, 0xad, 0xc3, 0x9f, 0x9d, 0xa5, 0xda, 0xef,
	0xb0, 0x81, 0xf3, 0x7e, 0xf2, 0xf4, 0xf7, 0xf4, 0x84, 0xe8, 0xe3, 0x93, 0x64, 0x76, 0x28, 0xf2,
	0xcd, 0x82, 0xc6, 0x7f, 0xb0, 0x6a, 0x6d, 0xed, 0x7e, 0xfc, 0x7e, 0xf1, 0xd0, 0xaa, 0xc5, 0xb0,
	0x8a, 0x9f, 0x7f, 0x25, 0x12, 0x15, 0xc9, 0x73, 0xf2, 0x2b, 0xe4, 0x27, 0x1b, 0x26, 0x59, 0x84,
	0x74, 0x69, 0x0d, 0xdd, 0xda, 0xb9, 0x86, 0x1c, 0x17, 0xfb, 0xe6, 0x8b, 0xd7, 0xbf, 0xb8, 0xef,
	0x85, 0xea, 0x8f, 0x8e, 0x2a, 0xbd, 0x28, 0xac, 0x62, 0xd6, 0xb7, 0x22, 0x32, 0x82, 0x59, 0xa0,
	0xe3, 0xa3, 0xea, 0x95, 0x0b, 0xf5, 0xf7, 0xf1, 0xd1, 0x85, 0x7a, 0xb4, 0x8c, 0x73, 0xe6, 0xf1,
	0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x73, 0x94, 0xed, 0x32, 0x80, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SerumOrderTrackerClient is the client API for SerumOrderTracker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SerumOrderTrackerClient interface {
	TrackOrder(ctx context.Context, in *TrackOrderRequest, opts ...grpc.CallOption) (SerumOrderTracker_TrackOrderClient, error)
}

type serumOrderTrackerClient struct {
	cc *grpc.ClientConn
}

func NewSerumOrderTrackerClient(cc *grpc.ClientConn) SerumOrderTrackerClient {
	return &serumOrderTrackerClient{cc}
}

func (c *serumOrderTrackerClient) TrackOrder(ctx context.Context, in *TrackOrderRequest, opts ...grpc.CallOption) (SerumOrderTracker_TrackOrderClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SerumOrderTracker_serviceDesc.Streams[0], "/dfuse.solana.serumhist.v1.SerumOrderTracker/TrackOrder", opts...)
	if err != nil {
		return nil, err
	}
	x := &serumOrderTrackerTrackOrderClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SerumOrderTracker_TrackOrderClient interface {
	Recv() (*OrderTransition, error)
	grpc.ClientStream
}

type serumOrderTrackerTrackOrderClient struct {
	grpc.ClientStream
}

func (x *serumOrderTrackerTrackOrderClient) Recv() (*OrderTransition, error) {
	m := new(OrderTransition)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SerumOrderTrackerServer is the server API for SerumOrderTracker service.
type SerumOrderTrackerServer interface {
	TrackOrder(*TrackOrderRequest, SerumOrderTracker_TrackOrderServer) error
}

// UnimplementedSerumOrderTrackerServer can be embedded to have forward compatible implementations.
type UnimplementedSerumOrderTrackerServer struct {
}

func (*UnimplementedSerumOrderTrackerServer) TrackOrder(req *TrackOrderRequest, srv SerumOrderTracker_TrackOrderServer) error {
	return status.Errorf(codes.Unimplemented, "method TrackOrder not implemented")
}

func RegisterSerumOrderTrackerServer(s *grpc.Server, srv SerumOrderTrackerServer) {
	s.RegisterService(&_SerumOrderTracker_serviceDesc, srv)
}

func _SerumOrderTracker_TrackOrder_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TrackOrderRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SerumOrderTrackerServer).TrackOrder(m, &serumOrderTrackerTrackOrderServer{stream})
}

type SerumOrderTracker_TrackOrderServer interface {
	Send(*OrderTransition) error
	grpc.ServerStream
}

type serumOrderTrackerTrackOrderServer struct {
	grpc.ServerStream
}

func (x *serumOrderTrackerTrackOrderServer) Send(m *OrderTransition) error {
	return x.ServerStream.SendMsg(m)
}

var _SerumOrderTracker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dfuse.solana.serumhist.v1.SerumOrderTracker",
	HandlerType: (*SerumOrderTrackerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TrackOrder",
			Handler:       _SerumOrderTracker_TrackOrder_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dfuse/solana/serumhist/v1/serumhist.proto",
}

// SerumHistoryClient is the client API for SerumHistory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SerumHistoryClient interface {
	GetFills(ctx context.Context, in *GetFillsRequest, opts ...grpc.CallOption) (*FillsResponse, error)
}

type serumHistoryClient struct {
	cc *grpc.ClientConn
}

func NewSerumHistoryClient(cc *grpc.ClientConn) SerumHistoryClient {
	return &serumHistoryClient{cc}
}

func (c *serumHistoryClient) GetFills(ctx context.Context, in *GetFillsRequest, opts ...grpc.CallOption) (*FillsResponse, error) {
	out := new(FillsResponse)
	err := c.cc.Invoke(ctx, "/dfuse.solana.serumhist.v1.SerumHistory/GetFills", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SerumHistoryServer is the server API for SerumHistory service.
type SerumHistoryServer interface {
	GetFills(context.Context, *GetFillsRequest) (*FillsResponse, error)
}

// UnimplementedSerumHistoryServer can be embedded to have forward compatible implementations.
type UnimplementedSerumHistoryServer struct {
}

func (*UnimplementedSerumHistoryServer) GetFills(ctx context.Context, req *GetFillsRequest) (*FillsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFills not implemented")
}

func RegisterSerumHistoryServer(s *grpc.Server, srv SerumHistoryServer) {
	s.RegisterService(&_SerumHistory_serviceDesc, srv)
}

func _SerumHistory_GetFills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SerumHistoryServer).GetFills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dfuse.solana.serumhist.v1.SerumHistory/GetFills",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SerumHistoryServer).GetFills(ctx, req.(*GetFillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SerumHistory_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dfuse.solana.serumhist.v1.SerumHistory",
	HandlerType: (*SerumHistoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFills",
			Handler:    _SerumHistory_GetFills_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dfuse/solana/serumhist/v1/serumhist.proto",
}
