// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: sf/solana/type/v1/account.proto

package pbsol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint64                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	ParentSlot    uint64                 `protobuf:"varint,3,opt,name=parent_slot,json=parentSlot,proto3" json:"parent_slot,omitempty"`
	ParentHash    string                 `protobuf:"bytes,4,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Accounts      []*Account             `protobuf:"bytes,7,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountBlock) Reset() {
	*x = AccountBlock{}
	mi := &file_sf_solana_type_v1_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountBlock) ProtoMessage() {}

func (x *AccountBlock) ProtoReflect() protoreflect.Message {
	mi := &file_sf_solana_type_v1_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountBlock.ProtoReflect.Descriptor instead.
func (*AccountBlock) Descriptor() ([]byte, []int) {
	return file_sf_solana_type_v1_account_proto_rawDescGZIP(), []int{0}
}

func (x *AccountBlock) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *AccountBlock) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *AccountBlock) GetParentSlot() uint64 {
	if x != nil {
		return x.ParentSlot
	}
	return 0
}

func (x *AccountBlock) GetParentHash() string {
	if x != nil {
		return x.ParentHash
	}
	return ""
}

func (x *AccountBlock) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AccountBlock) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Owner         []byte                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Deleted       bool                   `protobuf:"varint,7,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_sf_solana_type_v1_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_sf_solana_type_v1_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_sf_solana_type_v1_account_proto_rawDescGZIP(), []int{1}
}

func (x *Account) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Account) GetOwner() []byte {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *Account) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Account) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_sf_solana_type_v1_account_proto protoreflect.FileDescriptor

const file_sf_solana_type_v1_account_proto_rawDesc = "" +
	"\n" +
	"\x1fsf/solana/type/v1/account.proto\x12\x11sf.solana.type.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xea\x01\n" +
	"\fAccountBlock\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x1f\n" +
	"\vparent_slot\x18\x03 \x01(\x04R\n" +
	"parentSlot\x12\x1f\n" +
	"\vparent_hash\x18\x04 \x01(\tR\n" +
	"parentHash\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x126\n" +
	"\baccounts\x18\a \x03(\v2\x1a.sf.solana.type.v1.AccountR\baccounts\"g\n" +
	"\aAccount\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\fR\x05owner\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x18\n" +
	"\adeleted\x18\a \x01(\bR\adeletedBEZCgithub.com/streamingfast/firehose-solana/pb/sf/solana/type/v1;pbsolb\x06proto3"

var (
	file_sf_solana_type_v1_account_proto_rawDescOnce sync.Once
	file_sf_solana_type_v1_account_proto_rawDescData []byte
)

func file_sf_solana_type_v1_account_proto_rawDescGZIP() []byte {
	file_sf_solana_type_v1_account_proto_rawDescOnce.Do(func() {
		file_sf_solana_type_v1_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_solana_type_v1_account_proto_rawDesc), len(file_sf_solana_type_v1_account_proto_rawDesc)))
	})
	return file_sf_solana_type_v1_account_proto_rawDescData
}

var file_sf_solana_type_v1_account_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sf_solana_type_v1_account_proto_goTypes = []any{
	(*AccountBlock)(nil),          // 0: sf.solana.type.v1.AccountBlock
	(*Account)(nil),               // 1: sf.solana.type.v1.Account
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_sf_solana_type_v1_account_proto_depIdxs = []int32{
	2, // 0: sf.solana.type.v1.AccountBlock.timestamp:type_name -> google.protobuf.Timestamp
	1, // 1: sf.solana.type.v1.AccountBlock.accounts:type_name -> sf.solana.type.v1.Account
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sf_solana_type_v1_account_proto_init() }
func file_sf_solana_type_v1_account_proto_init() {
	if File_sf_solana_type_v1_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_solana_type_v1_account_proto_rawDesc), len(file_sf_solana_type_v1_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sf_solana_type_v1_account_proto_goTypes,
		DependencyIndexes: file_sf_solana_type_v1_account_proto_depIdxs,
		MessageInfos:      file_sf_solana_type_v1_account_proto_msgTypes,
	}.Build()
	File_sf_solana_type_v1_account_proto = out.File
	file_sf_solana_type_v1_account_proto_goTypes = nil
	file_sf_solana_type_v1_account_proto_depIdxs = nil
}
